# Define a Service to Expose orders microservice to Other Services within Cluster
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: orders-service  # DNS name
    labels:
      app: orders-service
  spec:
    ports: 
      - port: 80
        targetPort: 8091
        protocol: TCP
    type: ClusterIP
    selector:
      app: orders-service   # orders-service Pod should contain same labels
# Define a Deployment to configure orders-service on server
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: orders-service-deployment
    labels:
      app: orders-service
  spec:
    replicas: 1
    selector:
      matchLabels: 
        app: orders-service   # orders-service Pod should contain same labels
    template:
      metadata:
        labels:
          app: orders-service
      spec:
          containers:
            - name: orders-service
              image: djvjaysingh/orders-service
              env: # Setting Environment Variables
                - name: JAEGER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: nagp-service-app-config   # ConfigMap Name
                      key: JAEGER_HOST
              ports:
                - containerPort: 8091