# Define a Service to Expose aggregator microservice externally to the internet, which can be access from outside the Cluster
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: aggregator-service  # DNS name
    labels:
      app: aggregator-service
  spec:
    ports: 
      - port: 80
        targetPort: 8080
        protocol: TCP
    selector:
      app: aggregator-service   # aggregator-service Pod should contain same labels
    type: LoadBalancer  
# Define a Deployment to configure aggregator-service on server
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aggregator-service-deployment
    labels:
      app: aggregator-service
  spec:
    replicas: 1
    selector:
      matchLabels: 
        app: aggregator-service   # aggregator-service Pod should contain same labels
    template:
      metadata:
        labels:
          app: aggregator-service
      spec:
          containers:
            - name: aggregator-service
              image: djvjaysingh/aggregator-service
              env: # Setting Environment Variables
                - name: USER_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: nagp-service-app-config  # ConfigMap Name
                      key: USER_SERVICE_URL
                - name: ORDERS_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: nagp-service-app-config   # ConfigMap Name
                      key: ORDERS_SERVICE_URL
                - name: JAEGER_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: nagp-service-app-config   # ConfigMap Name
                      key: JAEGER_HOST
              ports:
                - containerPort: 8080